## Fichier : docker-compose.yml
version: '3.8'

services:
  nami:
    image: nginx
    container_name: nami
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - '80:80'
    restart: always
